format = """
$directory\
$git_branch\
$git_status\
$fill\
$azure\
$docker_context\
$cmd_duration\
$time\
$line_break\
$character"""



add_newline = true
palette = 'tokyo_night'


[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true

[time]
style = 'blue'
disabled = false
format = '[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '-5'
time_range = '10:00:00-14:00:00'



[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']


[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[palettes.tokyo_night]
dark_blue = '#7aa2f7'
blue = '#7dcfff'
teal = '#7dcfff'
red = '#f7768e'
orange = '#ff9e64'
green = '#9ece6a'
yellow = '#e0af68'
purple = '#bb9af7'
gray = '#414868'
black = '#24283b'
white = '#c0caf5'